#!/bin/sh /etc/rc.common
# mihomo-traffic：按来源设备 / 出口节点 / 目标累计 OpenClash(mihomo) 流量，见 /usr/bin/mihomo-traffic

# shellcheck disable=SC2034 # 由 /etc/rc.common 读取
START=99
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/mihomo-traffic run
	procd_set_param nice 19
	procd_set_param respawn 3600 10 0
	procd_set_param stderr 1
	procd_close_instance
}
